### PR TITLE
created custom scrollbar #242

### PR DESCRIPTION
**Pull request by ninman27**
Created custom scrollbar 

scrollbar

custom scrollbar 01

### CODE REVIEW

**Review by RevanchistX — COMMENTED** [review]
LGTM, my only question - are we going to have a dark/light themed scroll?
@edichoska

**Comment by edichoska** [comment]
@ninman27 Great start!
Can we make it shorter and skinnier? 
Also the gradient to be more apparent.

**Comment by ninman27** [comment]
scrollbar0625rem

**Review by edichoska — COMMENTED** [review]
use this for the gradient of the scrollbar:
linear-gradient(180deg, rgba(249,101,72,1) 0%, rgba(248,105,70,1) 38%, rgba(247,145,30,1) 79%);

**Review by edichoska — DISMISSED** [review]
👏 
@ninman27 just resolve the conflicts, everything else looks good.

**Review by edichoska — APPROVED** [review]

**Pull request merged**
