### PR TITLE
#147 - fixed blogs layout

### PR DESCRIPTION
**Pull request by kire21**
- added breakpoints in style
- fixed layout style
- fixed layout responsiveness
- created ScrollToTop component and implemented in blogs layout

viber_image_2024-04-19_11-47-53-323
viber_image_2024-04-19_11-47-34-622
viber_image_2024-04-19_11-47-00-573
viber_image_2024-04-19_11-46-45-926

### CODE REVIEW

**Review by edichoska — APPROVED** [review]
@kire21 The layout looks much better. Thank you for making the changes.
Can you just make the **back to top button** smaller, and the animation should be smoother.(going to the top of the page and also the button disappearing.)

**Review by edichoska — CHANGES_REQUESTED** [review]
Also I don't think the cards look good like this. But we are changing the design anyways.

**Comment by kire21** [comment]
> @kire21 The layout looks much better. Thank you for making the changes. Can you just make the **back to top button** smaller, and the animation should be smoother.(going to the top of the page and also the button disappearing.)

OK. I will make these changes. :)

**Review by stoimenov95 — CHANGES_REQUESTED** [review]
What do you think about adding some hover effect on the scroll to top btn?

**Comment by kire21** [comment]
> @kire21 What do you think about adding some hover effect on the scroll to top btn?

It is a good idea!

**Comment by kire21** [comment]
Screenshot from 2024-04-22 09-44-23

Screenshot from 2024-04-22 09-44-30

**Review by edichoska — APPROVED** [review]
💅

**Review by stoimenov95 — APPROVED** [review]
Perfect job @kire21 🥳

**Pull request merged**
