### PR TITLE
#178 FAQ restyling

### PR DESCRIPTION
**Pull request by MarijaTrajkoska**
Initial changes for FAQ Restyling

### CODE REVIEW

**Comment by stoimenov95** [comment]
@MarijaTrajkoska can we switch the branch for merging into from `main` to `staging`?

**Comment by stoimenov95** [comment]
This section's background should be aligned with the light/dark theme.

**Review by stoimenov95 — CHANGES_REQUESTED** [review]
Please adjust the light/dark background and the sections' height.

**Comment by edichoska** [comment]
Screenshot 2024-05-02 at 19 19 51
Great progress Marija! This looks exactly like the Figma Design so overall you have done an awesome job.
Just something small we have to fix:
When container explands the white background should follow. They shouldn't spill into the Contact Section. See the image for reference
@MarijaTrajkoska

**Review by edichoska — APPROVED** [review]

**Comment by edichoska** [comment]
@MarijaTrajkoska  please merge this 🙏

**Review by RevanchistX — APPROVED** [review]
LGTM

**Review by RevanchistX — APPROVED** [review]
LGTM

**Comment by edichoska** [comment]
> Please adjust the light/dark background and the sections' height.

@stoimenov95  please approve

**Pull request merged**
