### PR TITLE
jest setup

### PR DESCRIPTION
**Pull request by DimitarHristovski**

### CODE REVIEW

**Comment by stoimenov95** [comment]
Hey @DimitarHristovski, why do we need this PR besides the previous one? Did you have some trouble with merging/resolving conflicts there?

**Comment by DimitarHristovski** [comment]
@stoimenov95 Yes there were some problems with husky... but new branch was the right move, it took like 30min now its better it looks better and the naming of the branch is like the other branches
check if this is ok and tell me

**Comment by stoimenov95** [comment]
@DimitarHristovski All right, sometimes that can be helpful but we try to avoid that in order to preserve review history, comments, etc. Let's make this an exception and in the future please try and resolve the conflicts on the existing branch. FYI you can also rename the already-created branch if you step into that scenario again.

For me, this initial setup seems all right, I will share a link for all of the steps when working on a feature in this project, I just need to sort out some details first.

**Comment by edichoska** [comment]
> @stoimenov95 Yes there were some problems with husky... but new branch was the right move, it took like 30min now its better it looks better and the naming of the branch is like the other branches check if this is ok and tell me

Can you share what the husky problems were? Maybe we need to change/fix something

**Comment by DimitarHristovski** [comment]
> > @stoimenov95 Yes there were some problems with husky... but new branch was the right move, it took like 30min now its better it looks better and the naming of the branch is like the other branches check if this is ok and tell me
> 
> Can you share what the husky problems were? Maybe we need to change/fix something

i dont know what where the problems... but i have created a branch from the latest main update and it works fine now.I think they were package.json changes.If in the future there are gonna be problems with husky ill let you know

**Comment by stoimenov95** [comment]
@DimitarHristovski I've waited on closing this review because I wanted to share some details with you regarding the workflow we have on this project - https://github.com/learnhubmkd/app/wiki. 

Please delete your old branch when you can.

**Comment by stoimenov95** [comment]
@DimitarHristovski @edichoska FYI New PR will be created.

**Pull request closed without merging**
