### PR TITLE
#71 - fe create the LearnHub.mk Animation

### PR DESCRIPTION
**Pull request by Ultral1sk**

### CODE REVIEW

**Review by edichoska — CHANGES_REQUESTED** [review]
@Ultral1sk  The LearnHub.mk animation should not fade. It looks pretty cool now, but  just remove the fading.
Also this PR is just for that and not for the Vision and Mission section which contains the. Vision and Mission cards and the animation with them.
I will rename this PR. And create another tiket just for this and assign it to you.

**Comment by stoimenov95** [comment]
@Ultral1sk we discussed with @edichoska and the fade is all right. However, it would look great if we could start the animation again right after the fade out begins and not wait that long.

**Comment by Ultral1sk** [comment]
@stoimenov95 , @edichoska. Sorry for my late reply.
Discussed issues:
1. Fade at the end of animation
2. Starting the animation immediately after it ends.

- Since you guys have discussed it, I will leave it as it is.
- The animation in my eyes is really aggressive if it starts immediately after finishing.

**Comment by edichoska** [comment]
> @stoimenov95 , @edichoska. Sorry for my late reply. Discussed issues:
> 
> 1. Fade at the end of animation
> 2. Starting the animation immediately after it ends.
> 
> * Since you guys have discussed it, I will leave it as it is.
> * The animation in my eyes is really aggressive if it starts immediately after finishing.

@Ultral1sk  Can you share a video of how it would looks if it starts immediately?
The user won't spend a lot of time in each section, and as she/he skims through the sections, it would look like the animation is loaded just once(since now it takes it a couple of seconds to start again).

**Comment by Ultral1sk** [comment]
> > @stoimenov95 , @edichoska. Sorry for my late reply. Discussed issues:
> > 
> > 1. Fade at the end of animation
> > 2. Starting the animation immediately after it ends.
> > 
> > 
> > * Since you guys have discussed it, I will leave it as it is.
> > * The animation in my eyes is really aggressive if it starts immediately after finishing.
> 
> @Ultral1sk Can you share a video of how it would looks if it starts immediately? The user won't spend a lot of time in each section, and as she/he skims through the webside, it would look like the animation is loaded just once(since now it takes it a couple of seconds to start again).

Hey @edichoska, here you can see what the current animation looks like.
https://github.com/learnhubmkd/app/assets/52297047/0af397c4-26cc-48c7-9583-e05e5204309f

**Review by edichoska — APPROVED** [review]
Great work 👏

**Comment by RevanchistX** [comment]
@Ultral1sk 
What is this and why is it happening?
https://github.com/learnhubmkd/app/tree/71-fe-create-the-vissionmission-section/components/module-components
image

Cleanup your code before making merge requests.

@edichoska @stoimenov95 
This doesn't compile, how is it approved?

**Comment by edichoska** [comment]
@Ultral1sk  it seems like you accidentally deleted the learnhubAnimation.module.scss

**Comment by Ultral1sk** [comment]
> @Ultral1sk What is this and why is it happening? https://github.com/learnhubmkd/app/tree/71-fe-create-the-vissionmission-section/components/module-components image
> 
> Cleanup your code before making merge requests.
> 
> @edichoska @stoimenov95 This doesn't compile, how is it approved?
> 
> Edit: Animation looks good when I did a small quickfix.

@edichoska, @RevanchistX.  Folder name convention was wrong so I've created a new one and forgot to transfer the rest of the files in its respective folder.

**Comment by RevanchistX** [comment]
LGTM 🚀 

@Ultral1sk 
It happens, but make sure to recompile your build from time to time.
I usually rebuild the project per branch, just to make sure that I am seeing the real state of the branch.

@edichoska 
We can write some scripts to help devs do this faster as it can be a bothersome process.
If you want this, open a ticket for me.
Also, how did husky allow this break to happen?

**Review by RevanchistX — COMMENTED** [review]
LGTM 👍

**Review by RevanchistX — APPROVED** [review]

**Comment by Ultral1sk** [comment]
> LGTM 🚀
> 
> @Ultral1sk It happens, but make sure to recompile your build from time to time. I usually rebuild the project per branch, just to make sure that I am seeing the real state of the branch.
> 
> @edichoska We can write some scripts to help devs do this faster as it can be a bothersome process. If you want this, open a ticket for me. Also, how did husky allow this break to happen?

@RevanchistX - Regarding the build project issue, it is a valid point. But I do not think a build script is required, to me it seems like a premature optimization. But as you guys wish :D.
@edichoska - Seems like husky can't get a hang of me 🗡️  xD

Peace

**Review by stoimenov95 — APPROVED** [review]

**Pull request merged**
