### PR TITLE
#174 modified hero section

### PR DESCRIPTION
**Pull request by ninman27**
Modified hero section (I'm waiting for Kire to merge "fixed blog layout #147" and "reusable button component #181", to add the button in the hero section, and finish with responsiveness).

hero-screenshot

### CODE REVIEW

**Review by stoimenov95 — CHANGES_REQUESTED** [review]
Great job so far @ninman27, please remove the commented code. You can also create the PR as a draft pull request, when additional changes are expected.

**Review by stoimenov95 — CHANGES_REQUESTED** [review]
Screenshot 2024-04-23 at 23 51 52
The button should be aligned with the text.

**Comment by ninman27** [comment]
@stoimenov95 fixed with the last commit :)
hero-screen-shot

**Review by stoimenov95 — APPROVED** [review]
Great work @ninman27 🤘
Can you check if the button is aligned on all resolutions?

**Pull request merged**
